# Generated by Django 4.1.7 on 2023-04-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='edata',
            fields=[
                ('userid', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('elet', models.TextField(null=True)),
            ],
        ),
    ]
