# Generated by Django 4.2.2 on 2023-07-28 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('link', models.TextField()),
                ('description', models.TextField()),
                ('prev_id', models.TextField(null=True)),
                ('next_id', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='predictionresult',
            fields=[
                ('id', models.TextField(auto_created=True, primary_key=True, serialize=False)),
                ('result', models.TextField()),
                ('date', models.TextField()),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='eledata',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('report_time', models.DateField()),
                ('daliyusage', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
