# Generated by Django 4.2.2 on 2023-07-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='next_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='prev_id',
            field=models.TextField(null=True),
        ),
    ]
