# Generated by Django 4.2.2 on 2023-08-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_predictionresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='date',
            field=models.DateField(),
        ),
    ]
