# Generated by Django 4.2.2 on 2023-10-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_predictionresult_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
