# Generated by Django 4.2.2 on 2023-10-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_predictionresult_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='checked',
            field=models.IntegerField(default=7),
        ),
    ]
